name: Windows AnyDesk Session

on:
  workflow_dispatch:

jobs:
  anydesk-connect:
    runs-on: windows-latest
    steps:
      - name: Download AnyDesk
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "$env:USERPROFILE\AnyDesk.exe"

      - name: Start AnyDesk and display session info
        shell: pwsh
        run: |
          Start-Process -FilePath "$env:USERPROFILE\AnyDesk.exe" -ArgumentList "--start-service" -WindowStyle Minimized
          Start-Sleep -Seconds 10

          # Try to get the AnyDesk ID (best effort)
          $adcfg = "$env:APPDATA\AnyDesk\service.conf"
          $id = ""
          if (Test-Path $adcfg) {
            $bytes = [System.IO.File]::ReadAllBytes($adcfg)
            $idx = [Array]::IndexOf($bytes,0x0A,0)
            if ($idx -gt 0) {
              $id = [System.Text.Encoding]::UTF8.GetString($bytes,0,$idx)
            }
          }
          if (-not $id) {
            Write-Host "Unable to read AnyDesk ID from config file. You may need to connect using the runner's public IP or check the runner's desktop."
          }
          Write-Host "======================="
          Write-Host "AnyDesk is running!"
          Write-Host "AnyDesk ID (if available): $id"
          Write-Host "If ID is not shown, connect using the runner's public IP and check the desktop for the AnyDesk window."
          Write-Host "Session will end after 5 hours (max GitHub runner time)."
          Write-Host "======================="

      - name: Keep runner alive for 5 hours
        shell: pwsh
        run: |
          Write-Host "Sleeping for 5 hours (18000 seconds) to keep AnyDesk session alive..."
          Start-Sleep -Seconds 18000
