name: Windows RDP Session

on:
  workflow_dispatch:

jobs:
  enable-rdp:
    runs-on: windows-latest
    steps:
      - name: Enable RDP, set password, print credentials
        shell: pwsh
        run: |
          function New-RandomPassword($length = 20, $nonAlphanumericCount = 3) {
            $alpha = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
            $digits = '0123456789'
            $special = '!@#$%^&*-_=+[]{}'
            $all = ($alpha + $digits + $special).ToCharArray()
            $pw = -join ((1..($length - $nonAlphanumericCount)) | ForEach-Object { $all | Get-Random })
            $pw += -join ((1..$nonAlphanumericCount) | ForEach-Object { $special | Get-Random })
            ($pw.ToCharArray() | Sort-Object {Get-Random}) -join ''
          }
          $Password = New-RandomPassword 20 3
          $User = "$env:USERNAME"
          net user $User $Password

          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          $IP = (Invoke-WebRequest -UseBasicParsing -Uri "https://api.ipify.org").Content
          Write-Host "=========================================="
          Write-Host "RDP Enabled!"
          Write-Host "IP: $IP"
          Write-Host "Username: $User"
          Write-Host "Password: $Password"
          Write-Host "=========================================="
          Write-Host "Connect using Microsoft Remote Desktop."
          Write-Host "Session will end after 6 hours (max GitHub runner time)."
