name: Ubuntu RDP with Serveo Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Install desktop environment and xrdp
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          echo "startxfce4" > ~/.xsession
          sudo service xrdp restart

      - name: Start Serveo SSH tunnel for RDP (port 3389)
        run: |
          nohup ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net > serveo.log 2>&1 &
          sleep 10

      - name: Show Serveo public address
        run: |
          grep -Eo 'Forwarding.*serveo.net' serveo.log || cat serveo.log

      - name: Keep runner alive for 3 hours
        run: sleep 10800
