name: Windows Cloudflared Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: windows-latest
    steps:
      - name: Download cloudflared
        run: |
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

      # EXAMPLE: Tunnel a local web server on port 8080
      # If you want to tunnel RDP (port 3389) on a self-hosted runner, change 8080 to 3389
      - name: Start cloudflared tunnel to localhost:8080
        run: |
          Start-Process -NoNewWindow -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url http://localhost:8080 --no-autoupdate" 
          Start-Sleep -Seconds 10

      - name: Keep runner alive for 3 hours
        run: Start-Sleep -Seconds 10800
