name: Ubuntu RDP with Cloudflared Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Install desktop environment and xrdp
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          echo "startxfce4" > ~/.xsession
          sudo service xrdp restart

      - name: Download cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Start cloudflared tunnel to RDP port 3389
        run: |
          nohup cloudflared tunnel --url tcp://localhost:3389 --no-autoupdate > cloudflared.log 2>&1 &
          sleep 5

      - name: Show tunnel info
        run: |
          cat cloudflared.log | grep -Eo 'tcp://[a-zA-Z0-9\.-]+:[0-9]+'

      - name: Keep runner alive for 3 hours
        run: sleep 10800
