name: Windows RustDesk Session

on:
  workflow_dispatch:

jobs:
  rustdesk-connect:
    runs-on: windows-latest
    steps:
      - name: Download RustDesk
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-windows_x64.zip" -OutFile "rustdesk.zip"
          Expand-Archive -Path "rustdesk.zip" -DestinationPath "$env:USERPROFILE\rustdesk"
      
      - name: Start RustDesk in unattended mode
        shell: pwsh
        run: |
          $rustdeskPath = "$env:USERPROFILE\rustdesk\rustdesk.exe"
          # Generate a random password
          function New-RandomPassword($length = 8) {
            $alpha = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
            -join ((1..$length) | ForEach-Object { $alpha | Get-Random })
          }
          $Password = New-RandomPassword 12
          Start-Process -FilePath $rustdeskPath -ArgumentList "--password $Password" -WindowStyle Minimized
          Start-Sleep -Seconds 10 # Wait for RustDesk to initialize
          # Find the RustDesk ID in the logs
          $logFile = "$env:APPDATA\RustDesk\rustdesk-log.txt"
          $id = ""
          for ($i=0; $i -lt 30; $i++) {
            if (Test-Path $logFile) {
              $id = Select-String -Path $logFile -Pattern 'ID:[ ]*(\d+)' | Select-Object -Last 1 | ForEach-Object { $_.Matches[0].Groups[1].Value }
              if ($id) { break }
            }
            Start-Sleep -Seconds 2
          }
          Write-Host "======================="
          Write-Host "RustDesk is running!"
          Write-Host "ID: $id"
          Write-Host "Password: $Password"
          Write-Host "======================="
          Write-Host "Connect using your RustDesk client."
          Write-Host "Session will end after 5 hours (max GitHub runner time)."
      
      - name: Keep runner alive for 5 hours
        shell: pwsh
        run: |
          Write-Host "Sleeping for 5 hours (18000 seconds) to keep RustDesk session alive..."
          Start-Sleep -Seconds 18000
