name: Ubuntu RDP with Loophole Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Install desktop environment and xrdp
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          echo "startxfce4" > ~/.xsession
          sudo service xrdp restart

      - name: Download Loophole
        run: |
          wget -q https://github.com/loopholecloud/cli/releases/latest/download/loophole-linux-amd64
          sudo mv loophole-linux-amd64 /usr/local/bin/loophole
          sudo chmod +x /usr/local/bin/loophole

      - name: Start Loophole TCP tunnel to RDP port 3389
        run: |
          nohup loophole tcp 3389 --disable-clipboard --disable-auth > loophole.log 2>&1 &
          sleep 5

      - name: Show tunnel info
        run: |
          grep "Forwarding" loophole.log

      - name: Keep runner alive for 3 hours
        run: sleep 10800
